### ISSUE TITLE
Oops! Something went wrong and we couldn't connect to the conference: connection.otherError

### ISSUE THREAD

**Issue by hnyashiro** [igniterealtime/Openfire-Meetings#32]
help!pls!

**Comment by Chichocrates** [comment]
same problem for me!! I dont know what im doing wrong, with 4.0.1 all ok i upgrade and work all but webrct breaks with the same problem!!!!!

**Comment by Chichocrates** [comment]
Its some kind of problem with the plugin openfire websocket if you quit that plugin all will become to work, the ofmeet have less functions, but dele, guus and company are working for add again in the version 4.2.0 of openfire and 1.x of the plugin
I hope works for you!!!!!

**Comment by guusdk** [comment]
There's to little information in this issue to go on. From the top of my head, I can think of issues related to older versions of Openfire and the websockets plugin, as well as issues with ofmeet and offocus that might be causing problems. I advise you to update to the latest version of Openfire (which no longer requires a separate websockets plugin, and ofmeet/offocus.
