### ISSUE TITLE
Voice Calls

### ISSUE THREAD

**Issue by enlicayomer** [igniterealtime/Openfire-Meetings#47]
Hello Guys,
I want to make voice calls with SiP. What is the full path I need to follow?

**Comment by deleolajide** [comment]
Openfire Meetings does not currently support Jigasi SIP gateway for telephone calls. 

If you can read java code, have a look at the [ofswitch](https://github.com/Traderlynk/ofmeet-openfire-plugin/tree/master/ofswitch) plugin which is part of the Etherlynk fork of Openfire Meetings that integrates FreeSWITCH audio conferences with JitsiMeet video-conferences.

There is no documentation at the moment.

**Comment by guusdk** [comment]
I'm happy to report that Openfire meetings will support Jigasi starting with version 0.9.5!
