### ISSUE TITLE
Screen sharing unavailable with Chrome 63

### ISSUE THREAD

**Issue by ChristineBoersen** [igniterealtime/Openfire-Meetings#48]
The screen sharing feature doesn't appear to ofMeet users.

Using OpenFire 4.2.1, 
ofMeet and ofFocus 0.9.2,
and Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by deleolajide** [comment]
This is due because Chrome requires a custom extension based on individual user domains https://github.com/jitsi/jidesha

You need to create your a chrome extension for your own domain or use Pade.
