### ISSUE TITLE
A few connection issues

### ISSUE THREAD

**Issue by ageekhere** [igniterealtime/Openfire-Meetings#58]
Openfire 4.2.2
Openfire Focus Provider 0.9.3
Openfire Meetings 0.9.3

Took about 5 login attempts (have to retype username and password) to start a video call (without it crashing) here are the logs.

`2018.03.12 13:03:53 INFO [org.jitsi.videobridge.VideobridgeExpireThread]: org.jitsi.videobridge.Content - expire_content,conf_id=986a5f87a1549cb2,content=audio 
2018.03.12 13:03:53 INFO [org.jitsi.videobridge.VideobridgeExpireThread]: org.jitsi.videobridge.Content - expire_content,conf_id=986a5f87a1549cb2,content=video 
2018.03.12 13:03:53 INFO [org.jitsi.videobridge.VideobridgeExpireThread]: org.jitsi.videobridge.Content - expire_content,conf_id=986a5f87a1549cb2,content=data 
2018.03.12 13:03:53 INFO [org.jitsi.videobridge.VideobridgeExpireThread]: org.jitsi.videobridge.Conference - CAT=stat expire_conf,conf_id=8a05ab79963f9bcd duration=248,conf_count=1,ch_count=0,v_streams=0,conf_completed=2,no_payload_ch=2,no_transport_ch=2,total_ch=6,has_failed=false,has_partially_failed=false `

Also I can only have 2 users connected, when a third connects all the videos and mics get turned off, when a user leaves and the total users in the room is 2 then video and audio work again. How can I have more than 2 users video call?

**Comment by guusdk** [comment]
In Openfire Meetings 0.9.3, a meeting with exactly two participants will prefer a peer-to-peer connection between the participants to exchange audio and video data. When more participants join, all audio/video will be required to flow via Openfire (specifically, via the Jitsi Video Bridge instance that's part o the ofmeet plugin). When your network (or firewall) prevents this data from reaching Openfire, you'll notice that "the third person breaks the meeting" as is described by others in this issue. As soon as the amount of participants drops back to two, a peer-to-peer based exchange is realized again, which appears to "fix" the problem.

These kind of issues are infrastructure-related. There's not a lot we can do in Openfire to prevent them from occurring. If you're experiencing them, I advise you to:

- Update to ofmeet and offocus 0.9.3 or later
- Make sure that traffic can reach your Openfire server over ports 5222, 7443, 5000-6000 and 50000-6000 (TPC _and_ UDP) (actually, just one of these ranges is needed, but the range tends to differ)

If problems persist, examine your firewall logs.

**Comment by ageekhere** [comment]
Tested with 3 users on the local lan (not going through the firewall) same issue with video not working, going to look through my logs.

**Comment by Pn-nL** [comment]
> Tested with 3 users on the local lan (not going through the firewall) same issue with video not working, going to look through my logs.
> 
> Ok worked it out, mixing server FQDN and server IP address when logging clients in

What do you mean by "mixing server FQDN and server IP"?
I had tried everything, and it's not working with more than 2 users;
All the records need at DNS;
focus user withing the domain (as a domain user), with green light at the users list;
all firewall off (server and clients);
tried to use url with server IP address ( https://xxx.xxx.xxx.xxx:7443/ofmeet)
tried to use url with server's name (https://nnnnn:7443/ofmeet)
and with FQDN (https://nnnnn.ddddd.dd:7443/ofmeet)
 - all users are able to enter the room in the 3 ways, but after the third, audio and video are cut off

any other solution???

**Comment by deleolajide** [comment]
> any other solution???

This project is currently **not maintained**. Try the [Pade project](https://github.com/igniterealtime/openfire-pade-plugin/releases) for more up-to-date versions of the ofmeet and offocus plugins. Development will resume at some point in the future with Jitsi-Videobridge version 2.x as soon as [this PR](https://github.com/jitsi/jitsi-sctp/pull/3) is merged to enable support for Windows.

**Comment by ageekhere** [comment]
@Pn-nL  I have installed the jitsi meet server directly, it solved all the issues i had.
https://jitsi.org/downloads/

**Comment by deleolajide** [comment]
> @Pn-nL I have installed the jitsi meet server directly, it solved all the issues i had.
> https://jitsi.org/downloads/

Indeed it would :-)

Anyone trying to use Openfire Meetings wants to add video conferencing to chat and group chat with user authentication that Openfire offers. This integration of Jitsi with Openfire also offers a few more features not available in the standard jitsi meet server

![image](https://user-images.githubusercontent.com/110731/91704627-c5c4d900-eb73-11ea-82e8-3eb0925e1d11.png)

**Comment by Pn-nL** [comment]
> @Pn-nL I have installed the jitsi meet server directly, it solved all the issues i had.
> https://jitsi.org/downloads/

But my server openfire runs on server 2016.
as far as i read, jitsi only work on ubuntu, thas why i'm trying with ofmeet
