### ISSUE TITLE
When compile ofmeet-summary.jsp in eclipse there report can't find urlEncode function

### ISSUE THREAD

**Issue by cnscns** [igniterealtime/Openfire-Meetings#70]

**Comment by cnscns** [comment]
I replace urlEncode with URLEncoder.encode and compile success

**Comment by guusdk** [comment]
I'm guessing that Eclipse fails to pick up the `urlEncode` method that is provided by the 'admin' taglib. 

The ofmeet builds (including the continuous integration) does pre-compile these pages. As these builds do not fail, this problem appears to be an Eclipse issue, not an Openfire issue.

**Comment by cnscns** [comment]
Yes ,in Openfire 4.2.3 have this urlEncode tag.I want to debug openfire-meetings in eclipse,Is there any help documents?
