### ISSUE TITLE
Allow to customize config.js hosts -> domain property

### ISSUE THREAD

**Issue by nitomartinez** [igniterealtime/Openfire-Meetings#77]
Please allow to customize config.js hosts parameters. 

### Use case

When the domain used in Openfire is domain.com, and you use SRV registries to point to the right xmpp server, the jitsi url might be something different than domain.com. 

Example:

- Xmpp domain is domain.com
- Users are: user1@domain.com
- xmpp server is at: xmpp.domain.com with IP X.Y.Z.10
- there is SRV registry as 
`_xmpp-client._tcp.qindel.com. 900 IN	SRV	5 0 5222 xmpp.qindel.com.`
- web site is at:  qindel.com with IP X.Y.Z.11

With this configuration the share extension does not work, as it uses the domain->hosts entry to point to the browser url.

### Example config.js

This the autogenerated config.js from the configuration servlet

<pre>
  "hosts": {
    "domain": "domain.com",
    "focus": "focus.domain.com",
    "muc": "conference.domain.com",
    "bridge": "jitsi-videobridge.domain.com"
  },
</pre>

But according to the use case above it should be something like:

<pre>
  "hosts": {
    "domain": "jitsi.domain.com",
    "focus": "focus.domain.com",
    "muc": "conference.domain.com",
    "bridge": "jitsi-videobridge.domain.com"
  },
</pre>

### Proposal

Allow to configure the config.js settings with configuration properties like:

- org.jitsi.videobridge.ofmeet.hosts.domain
- org.jitsi.videobridge.ofmeet.hosts.muc
- org.jitsi.videobridge.ofmeet.hosts.bridge
- org.jitsi.videobridge.ofmeet.hosts.focus

### Full config.js
Example full config.js
<pre>
var config = {
  "useNicks": false,
  "disableAudioLevels": false,
  "useIPv6": false,
  "webrtcIceTcpDisable": false,
  "defaultSipNumber": "",
  "startBitrate": 800,
  "enableWelcomePage": true,
  "useStunTurn": false,
  "enableRtpStats": true,
  "bosh": "wss://jitsi.domain.com:7443/ws/",
  "enableRecording": false,
  "resolution": 720,
  "constraints": {"video": {
    "aspectRatio": 16 / 9,
    "height": {
      "ideal": 720,
      "min": 240,
      "max": 2160
    }
  }},
  "hiddenDomain": "recorder.domain.com",
  "enableLipSync": false,
  "minHDHeight": 540,
  "useRoomAsSharedDocumentName": false,
  "recordingType": "colibri",
  "desktopSharingChromeMinExtVersion": "0.1.6.4",
  "startAudioMuted": 9,
  "openSctp": true,
  "clientNode": "http://igniterealtime.org/ofmeet/jitsi-meet/",
  "conferences": [],
  "channelLastN": -1,
  "desktopSharingFirefoxDisabled": false,
  "adaptiveLastN": false,
  "desktopSharingChromeExtId": "ehedngmcebdodaehdjbfpbogogehocml",
  "hosts": {
    "domain": "domain.com",
    "focus": "focus.domain.com",
    "muc": "conference.domain.com",
    "bridge": "jitsi-videobridge.domain.com"
  },
  "logStats": false,
  "useRtcpMux": true,
  "requireDisplayName": false,
  "startVideoMuted": 9,
  "adaptiveSimulcast": true,
  "enforcedBridge": "jitsi-videobridge.domain.com",
  "useBundle": true,
  "p2p": {
    "disableH264": false,
    "preferH264": true,
    "useStunTurn": false,
    "enabled": true
  },
  "desktopSharingChromeDisabled": false,
  "disableRtx": true,
  "disableAdaptiveSimulcast": false,
  "desktopSharingChromeSources": [
    "screen",
    "window",
    "tab"
  ],
  "webrtcIceUdpDisable": false,
  "disableSimulcast": false,
  "startAudioOnly": false,
  "stereo": false,
  "focusUserJid": "focus@domain.com"
};
</pre>

**Comment by deleolajide** [comment]
This issue has expired
