### ISSUE TITLE
404

### ISSUE THREAD

**Issue by ZeeshanSultan** [igniterealtime/Openfire-Meetings#81]
I have installed the ofmeet plugin but even after installation i don't see a new configuration page and can't access the given url in the documentation
<img width="833" alt="screen shot 2018-09-26 at 4 26 24 pm" src="https://user-images.githubusercontent.com/8667667/46077051-f0989c80-c1a8-11e8-8d98-2f1277b13694.png">

**Comment by deleolajide** [comment]
> i don't see a new configuration page

Something wrong with your openfire meetings installation. check the openfire log files for errors

**Comment by ZeeshanSultan** [comment]
Got it.

`2018.09.26 11:09:15 org.jivesoftware.openfire.container.PluginManager - Ignoring plugin 'ofmeet': requires Java specification version 1.8. Openfire is currently running in Java 10. `
