### ISSUE TITLE
Room time configuration.

### ISSUE THREAD

**Issue by ZeeshanSultan** [igniterealtime/Openfire-Meetings#82]
Initially i wanted to create a room for x amount of time.
Also, is there an api which i can use to create rooms and assign users.

My use case is a dating platform like tinder but users get a 10 min videocall once they match.

PSEUDO
```
if (matched(x_user, y_user)) {
     room_url = create_room("10 minutes", "password123")
     sendmail(room_url, [x_user, y_user])
}
```

**Comment by deleolajide** [comment]
No, but you can always write your own web application to do this and create/destroy the rooms as you need them
