### ISSUE TITLE
Whiteboard plugin

### ISSUE THREAD

**Issue by ZeeshanSultan** [igniterealtime/Openfire-Meetings#84]
Is there a whiteboard plugin for ofmeet as mentioned in this document?
http://wikisuite.org/Openfire-Meetings

If yes, how to enable it?

**Comment by deleolajide** [comment]
No, there isn't one directly in Openfire Meetings plugin for Openfire. There is a drawing collaboration application for Pade which has to hosted on your own web server and can be found here https://github.com/igniterealtime/Pade/tree/master/apps
