### ISSUE TITLE
Openfire-Meetings视频聊天

### ISSUE THREAD

**Issue by qian9816** [igniterealtime/Openfire-Meetings#85]
Openfire-Meetings 视频聊天怎么嵌入到web网站，我将视频聊天地址放到web网站之后总是提示要验证用户身份，但是我的web网站已经登录了啊，转到视频聊天之后怎么去掉这个验证呢，直接就用我web网站的用户进行视频聊天。

**Comment by deleolajide** [comment]
Translated by google

>How does Openfire-Meetings video chat be embedded into a web site? I always prompt the user to verify the identity of the user after placing the video chat address on the web site, but my web site is already logged in. How do I remove this verification after going to the video chat? Video chat directly with users of my web site

![image](https://user-images.githubusercontent.com/110731/49082448-b186d600-f241-11e8-8ba8-64730ec9b263.png)
